version: '3.3'

services:
  db:    
    image: mysql:5.7
    networks: 
        - dev-network
    restart: always
    environment:
      MYSQL_DATABASE: 'curso_node'      
      MYSQL_USER: 'node'      
      MYSQL_PASSWORD: 's10121426'      
      MYSQL_ROOT_PASSWORD: 's10121426'
    ports:      
      - '3307:3306'
    expose:      
      - '3307'      
    volumes:
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:edge
    networks: 
        - dev-network
    links:
     - db
    ports:
    - "8080:80"
    environment:
     - PMA_HOST=db     
    depends_on:
        - "db" 

volumes:
  mysql-volume: 

networks: 
  dev-network:
      driver: bridge
